# Generated by Django 2.2.7 on 2020-07-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example2',
            name='curp',
            field=models.CharField(default=24, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example2',
            name='direccion',
            field=models.CharField(default=35, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example2',
            name='edad',
            field=models.PositiveIntegerField(default=346356),
            preserve_default=False,
        ),
    ]
