# Generated by Django 2.2.7 on 2020-07-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
